### ISSUE TITLE
Questions + suggestions for usability

### ISSUE THREAD

**Issue by pietergen** [dannysu/hash0#2]
Hi Danny, hope this is the right place for feature requests. I just discovered hash0 and I love the concept. I read in an older Hackernews post that you were looking for user feedback and ideas, If this is still the case, I have some ideas on improving usability, to make hash0 as easy to use as, say, Lastpass. But of course more secure.

**Comment by dannysu** [comment]
Sure! You can also email me anytime.

**Comment by pietergen** [comment]
Hi Danny, if it's fine with you I'll post it here, maybe it's useful for others too...... I have a list of features that woul dmake hash0 better in my opinion. I also have some questions.

FEATURES
A- a USERNAME field in the stored account settings. Sure, you could use the "Notes" field for that, but an explicit username field is more clear. I can't use the same user name on every site: sometime I don't want that, sometimes my usual name is already taken, sometimes the username is in fact a 2nd password which needs to be "strong"  as well.  Anyway, my usernames differ from site to site and I have to keep track of them somehow.....

B- CHOICE where to store account settings. An ideal choice would be: 
a) in the browser's local storage [- for maximum transparency the pathname should be given too.. so that users can inspect the file. But perhaps this is impractical? I'm not sure if the "file system hierarchy" within Firefox is different for say Linux, OSX or Windows.... ? ]
b) somewhere on the user's system, to be defined by user. Could be in /home/user; could be on a USB-stick; could be (on a Windows machine) in c:\user\mydocuments, etc. 
c) somewhere online, pathname (URL) to be defined by user
d) on a mobile device (see Question 3.) 

C- an AUTOFILL option, just like e.g. LastPass. This would greatly enhance usability. (And if improved usability increases the adoption of safer password managers, it improves security in the population as well.) 

D- make it MORE CLEAR that a site's password can be recalcuted without the need for a new masterword. This is a great feature! But imho the button style (a toggle) is less inutitive. So maybe a differenent button would work better

E- the possibility to CALCULATE A USERNAME. So, a user may chose his own username OR have one calculated for him by the program. [This is userful for cases like online banking, where one needs a strong username as an additional security measure. ]  This username is calculated once, and then stored in the account settings. Since we are not talking about a stateless scenario here, the username should (imho) not be calculated based on the masterpassword but randomly generated. Sources of entropy could be files on the users machine, mouse movements, keyboard strokes and so on (I think one could use /dev/random for that). 

QUESTIONS
1. is it possible to store the account settings on any online place (besides the App Engine places like Dropbox, OneDive, GoogleDrive, users' own webserver etc). ? 
2. where is the decryption of the account settings done? Client side, I suppose? How are they decrypted anyway? The salt is stored in those settings, right? ???
3. this may be far fetched or a bad idea, but here it goes: would it be possible to store the account settings on a mobile device and access those from the (PC) browser using ssh ? One might need an Android or iOS app, let's call it the "hash0 app". The app stores the account settings in a secure place on the phone and gives ssh-access to that file. What the (PC) Firefox-extension does, is getting a ssh-tunnel to the device. For added security, the phone app could ask for a confirmation. It could also encrypted the file (again), so that in case of theft of the phone, the thief now has an encrypted file of encrypted usernames and salts...   :-)   Please do tell me if I'm crazy.

**Comment by dannysu** [comment]
Cool, thanks for the suggestions Pieter.

You can definitely store the account metadata on your own server, but not Dropbox/OneDrive/GDrive. You should be able to password protect the metadata too. The https://github.com/dannysu/gae_storage project is a good example of how to go about implementing such a thing for your own server. See storage.py. You just need to be able to support POST and GET for the web app to storage and retrieve encrypted metadata.

The decryption is done on client side. The remote server never sees anything except encrypted stuff. The site specific salt is stored in the encrypted metadata, yes.

Regarding storing the encrypted blob on mobile phone, that should be possible, but not something I'd work on myself. But the stuff you talked about like getting a SSH tunnel going, that's compatible with hash0. You could store the data on a server that's only accessible by SSH tunneling and then just point the storage URL to the tunnel.

Regarding your suggestions, a username field and choice to store things locally might be something I work on, but can't promise when. The autofill option is something I might look into too. I haven't done it mainly because of the desire to not store master password in the browser.
